# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tokopedia Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tokopedia Test
  pod 'DLRadioButton', '~> 1.4'
  pod 'HandyJSON', '~> 4.1.1'
  pod 'WARangeSlider'
  pod 'Eatr'
  pod 'Nativefier'
  
  target 'Tokopedia TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tokopedia TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
